package com.asadulloh.quronozbek;

import java.util.ArrayList;
import java.util.List;

public class Sura {
    public static final String INFO = "3JzUSXSxXqk";
    public static final String AL_FOTIHA = "4WTShAOGXjQ";
    public static final String AL_BAQARA = "jolHhwbRiVw";
    public static final String OLI_IMRON = "mH40n89PQbo";
    public static final String AN_NISO = "k8rvmKswagA";
    public static final String AL_MOIDA = "iSFInuTz-5A";
    public static final String AL_ANOM = "KMrCqSCe0GI";
    public static final String AL_AROF = "unP38fb2-48";
    public static final String AL_ANFOL = "k4jK7lY9ZjM";
    public static final String AT_TAVBA = "KQ4F7yZh-Iw";
    public static final String YUNUS = "5cxWq2H64aU";
    public static final String HUD = "cswqyOp4PHU";
    public static final String YUSUF = "L2mZIc_aco8";
    public static final String ROD = "3E2YLDcx-a8";
    public static final String IBROHIM = "Fw-rec4eHDU";
    public static final String HIJR = "gpnRr1owk5Y";
    public static final String NAHL = "LAeNPBqOdFk";
    public static final String ISRO = "p2-6QV_zivE";
    public static final String KAHF = "E4creBXJbXM";
    public static final String MARYAM = "AHlVOD4U_3Q";
    public static final String TOHA = "qYklcJgJvxc";
    public static final String ANBIYO = "1QCYLaUmBbc";
    public static final String HAJ = "pKsKqVttLhM";
    public static final String MUMINUN = "WNuwirJGuro";
    public static final String NUR = "1eZduFb5Xo8";
    public static final String FURQON = "rk32wDDlyII";
    public static final String SHUARO = "gsohR8HorkY";
    public static final String NAML = "oNtG1ZSgf4A";
    public static final String QOSOS = "j8S--MOTj8c";
    public static final String ANKABUT = "fG_l6gWijCk";
    public static final String RUM = "g5Qw-PsCLys";
    public static final String LUQMON = "9ShIzC6vgGw";
    public static final String SAJDA = "Jegmnywfgus";
    public static final String AZHOB = "vhQtF0M7FaM";
    public static final String SABA = "t3a0DTnaj7Q";
    public static final String FOTIR = "MKyuHo3Skt0";
    public static final String YAASIN = "i57zSy2ovWM";
    public static final String SOFFAT = "zlyLBhyWGQA";
    public static final String SOD = "d68j4v1oKUs";
    public static final String ZUMAR = "m3KRYd8Xfiw";
    public static final String GOFIR = "Z9Y7wJPyoRE";
    public static final String FUSSILAT = "A4RPxp60r4A";
    public static final String SHUURO = "4hGPhxt-olM";
    public static final String ZUXRUF = "Sc4qtEbXEgo";
    public static final String DUXON = "sSk4SufZB2U";
    public static final String JOSIYA = "guEp31P4pBc";
    public static final String AHQOF = "piwj1HKNhtE";
    public static final String MUHAMMAD = "PRk0AD1g8oY";
    public static final String FATH = "pY9UwEVIwCw";
    public static final String HUJUROT = "3bxQuBgF7WY";
    public static final String QOF = "IZVRzgxUkSA";
    public static final String ZORIYOT = "QbXGVYCEnZs";
    public static final String TUR = "m_WoZANeU50";
    public static final String NAJM = "BaRK96ENT3M";
    public static final String QAMAR = "5AvR_XEnYGk";
    public static final String AR_ROHMAN = "I-t51epGs48";
    public static final String VOQIA = "kOloi0DxszU";
    public static final String HADID = "WBjW375ZNv4";
    public static final String MUJODALA = "H3zliqEqsd8";
    public static final String HASHR = "kUGZ54yabkk";
    public static final String MUMTAHANA = "SCU-P1HjBXQ";
    public static final String SOOFF = "zlyLBhyWGQA";
    public static final String JUMA = "cdSwDDnXuUg";
    public static final String MUNOFIQUN = "Ybk3DQFe7_o";
    public static final String TAGOBUN = "IG-GZq7w_5A";
    public static final String TALOQ = "GdyT7t0obao";
    public static final String TAHRIM = "JgnZcikmZfA";
    public static final String MULK = "Lj33k_48DIA";
    public static final String QALAM = "He8ivH7yhPw";
    public static final String HAAQQO = "2fwsU6ZH_l0";
    public static final String MAORIJ = "PXfIMVqob5w";
    public static final String NUH = "nK-iNNrkCNQ";
    public static final String JIN = "qVkm8b5baf8";
    public static final String MUZZAMMIL = "le7MIWgsHUY";
    public static final String MUDDASSIR = "JmYx55aHZkM";
    public static final String QIYAAMA = "u6kQKR79qhk";
    public static final String INSON = "bP2W6RB9RoU";
    public static final String MURSALAAT = "DCxv07UggLc";
    public static final String NABA = "TwUpAhiJGzg";
    public static final String NAZIAT = "lEb8o59ozwg";
    public static final String ABASA = "q7IJOlygy_w";
    public static final String TAKVIR = "XYhhRHWiKhc";
    public static final String INFITOR = "zRuVHfy9NzE";
    public static final String MUTOFFIFUN = "nuNvoT8xa18";
    public static final String INSHIQOQ = "keHP1At-PgY";
    public static final String BURUJ = "uNodzgVzn2g";
    public static final String TORIQ = "OigLs-IF7HQ";
    public static final String ALAA = "6ZQZgc0P2MY";
    public static final String GOSHIYA = "iPhdnWOGpdw";
    public static final String FAJR = "9y79hH4tYpQ";
    public static final String BALAD = "NgWhzR60V2M";
    public static final String SHAMS = "2iZavBcduRo";
    public static final String LAYL = "sBYAhTbvz-M";
    public static final String ZUHO = "JqoQRY-wBng";
    public static final String SHARH = "FuLSRnqtdV8";
    public static final String TIYN = "e3i5Y22mWL4";
    public static final String ALAQ = "LCRfKcqAIFw";
    public static final String QADR = "LO1e2-HOUpE";
    public static final String BAYYINA = "yOjgPpgtBeY";
    public static final String ZALZALA = "ABC_DNyxMyY";
    public static final String ADIYAT = "b-YsJQLMiZk";
    public static final String QORIA = "aWT96VhT9X4";
    public static final String TAKAASUR = "xxSMWxqaaNM";
    public static final String ASR = "TfwRtZbE2eM";
    public static final String HUMAZA = "DNiDHuVhZtQ";
    public static final String FIYL = "wXAFp0rwKHA";
    public static final String QURAYSH = "hdAt2PUk57I";
    public static final String MAAUUN = "8hwWWInZUC0";
    public static final String KAVSAR = "ya9wwiYtFZ4";
    public static final String KAAFIRUN = "n55-lD4h2jA";
    public static final String NASR = "x5adBPxHIdY";
    public static final String MASAD = "cZhzczO6tAI";
    public static final String IHLOS = "mhsyFOIrkdw";
    public static final String FALAQ = "-3hUG6IR2QE";
    public static final String NAAS = "TiurYna93Ks";

    public static final List<String> sura = new ArrayList<>();

    public static void initialize() {
        sura.add(INFO);
        sura.add(AL_FOTIHA);
        sura.add(AL_BAQARA);
        sura.add(OLI_IMRON);
        sura.add(AN_NISO);
        sura.add(AL_MOIDA);
        sura.add(AL_ANOM);
        sura.add(AL_AROF);
        sura.add(AL_ANFOL);
        sura.add(AT_TAVBA);
        sura.add(YUNUS);
        sura.add(HUD);
        sura.add(YUSUF);
        sura.add(ROD);
        sura.add(IBROHIM);
        sura.add(HIJR);
        sura.add(NAHL);
        sura.add(ISRO);
        sura.add(KAHF);
        sura.add(MARYAM);
        sura.add(TOHA);
        sura.add(ANBIYO);
        sura.add(HAJ);
        sura.add(MUMINUN);
        sura.add(NUR);
        sura.add(FURQON);
        sura.add(SHUARO);
        sura.add(NAML);
        sura.add(QOSOS);
        sura.add(ANKABUT);
        sura.add(RUM);
        sura.add(LUQMON);
        sura.add(SAJDA);
        sura.add(AZHOB);
        sura.add(SABA);
        sura.add(FOTIR);
        sura.add(YAASIN);
        sura.add(SOFFAT);
        sura.add(SOD);
        sura.add(ZUMAR);
        sura.add(GOFIR);
        sura.add(FUSSILAT);
        sura.add(SHUURO);
        sura.add(ZUXRUF);
        sura.add(DUXON);
        sura.add(JOSIYA);
        sura.add(AHQOF);
        sura.add(MUHAMMAD);
        sura.add(FATH);
        sura.add(HUJUROT);
        sura.add(QOF);
        sura.add(ZORIYOT);
        sura.add(TUR);
        sura.add(NAJM);
        sura.add(QAMAR);
        sura.add(AR_ROHMAN);
        sura.add(VOQIA);
        sura.add(HADID);
        sura.add(MUJODALA);
        sura.add(HASHR);
        sura.add(MUMTAHANA);
        sura.add(SOOFF);
        sura.add(JUMA);
        sura.add(MUNOFIQUN);
        sura.add(TAGOBUN);
        sura.add(TALOQ);
        sura.add(TAHRIM);
        sura.add(MULK);
        sura.add(QALAM);
        sura.add(HAAQQO);
        sura.add(MAORIJ);
        sura.add(NUH);
        sura.add(JIN);
        sura.add(MUZZAMMIL);
        sura.add(MUDDASSIR);
        sura.add(QIYAAMA);
        sura.add(INSON);
        sura.add(MURSALAAT);
        sura.add(NABA);
        sura.add(NAZIAT);
        sura.add(ABASA);
        sura.add(TAKVIR);
        sura.add(INFITOR);
        sura.add(MUTOFFIFUN);
        sura.add(INSHIQOQ);
        sura.add(BURUJ);
        sura.add(TORIQ);
        sura.add(ALAA);
        sura.add(GOSHIYA);
        sura.add(FAJR);
        sura.add(BALAD);
        sura.add(SHAMS);
        sura.add(LAYL);
        sura.add(ZUHO);
        sura.add(SHARH);
        sura.add(TIYN);
        sura.add(ALAQ);
        sura.add(QADR);
        sura.add(BAYYINA);
        sura.add(ZALZALA);
        sura.add(ADIYAT);
        sura.add(QORIA);
        sura.add(TAKAASUR);
        sura.add(ASR);
        sura.add(HUMAZA);
        sura.add(FIYL);
        sura.add(QURAYSH);
        sura.add(MAAUUN);
        sura.add(KAVSAR);
        sura.add(KAAFIRUN);
        sura.add(NASR);
        sura.add(MASAD);
        sura.add(IHLOS);
        sura.add(FALAQ);
        sura.add(NAAS);
        sura.add(NAAS);
    }

    public String getSura(int position) {
        return sura.get(position);
    }
}
